version: '3'
networks:
  backend:
    driver: bridge
services:
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
    environment:
      - MINIO_ACCESS_KEY=minio_access_key
      - MINIO_SECRET_KEY=minio_secret_key
      - MINIO_ROOT_USER=ROOTUSER
      - MINIO_ROOT_PASSWORD=CHANGEME123
    command: server /data
    volumes:
      - minio_data:/data
    networks:
      - backend

  mc:
    image: minio/mc:latest
    entrypoint: ["mc"]
    volumes:
      - ./mc-config:/root/.mc
      - ./mc-data:/root/.minio
    environment:
      - MC_HOST_minio=http://minio:9000
    depends_on:
      - minio
    networks:
      - backend

volumes:
  minio_data:
